"""
generate_architecture_diagrams.py — Render schematic pipeline diagrams for the README.

Produces assets/architecture.png (extraction -> steering -> evaluation pipeline)
and assets/steering_pipeline.png (single forward-pass steering intervention).
These are box-and-arrow schematics, not results plots — the actual result figures
live in results/emotion_refusal/figures/ and are generated by generate_figures.py.
"""

from pathlib import Path
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

OUT_DIR = Path(__file__).resolve().parent.parent / "assets"
OUT_DIR.mkdir(exist_ok=True)

BOX_COLOR = "#e8eef7"
BOX_EDGE = "#3a5a8c"
TEXT_COLOR = "#1a1a1a"
ARROW_COLOR = "#3a5a8c"


def draw_pipeline(steps: list[str], subtitles: list[str], save_path: Path, figsize=(13, 2.6)):
    n = len(steps)
    fig, ax = plt.subplots(figsize=figsize)
    ax.set_xlim(0, n)
    ax.set_ylim(0, 1)
    ax.axis("off")

    box_w, box_h = 0.82, 0.6
    for i, (step, sub) in enumerate(zip(steps, subtitles)):
        cx = i + 0.5
        rect = mpatches.FancyBboxPatch(
            (cx - box_w / 2, 0.5 - box_h / 2), box_w, box_h,
            boxstyle="round,pad=0.02,rounding_size=0.04",
            linewidth=1.5, edgecolor=BOX_EDGE, facecolor=BOX_COLOR,
        )
        ax.add_patch(rect)
        ax.text(cx, 0.58, step, ha="center", va="center", fontsize=10.5,
                 fontweight="bold", color=TEXT_COLOR, wrap=True)
        if sub:
            ax.text(cx, 0.34, sub, ha="center", va="center", fontsize=8,
                     color="#555555", wrap=True)
        if i < n - 1:
            ax.annotate(
                "", xy=(cx + 0.5 + (1 - box_w) / 2 - 0.02, 0.5),
                xytext=(cx + box_w / 2 + 0.02, 0.5),
                arrowprops=dict(arrowstyle="-|>", color=ARROW_COLOR, lw=1.5),
            )

    fig.tight_layout()
    fig.savefig(save_path, dpi=180, bbox_inches="tight")
    plt.close(fig)
    print(f"Wrote {save_path}")


def main():
    # Full extraction -> steering -> evaluation pipeline (src/ modules in flow order)
    draw_pipeline(
        steps=["Stories", "Activation\nExtraction", "Emotion\nVectors", "Forward\nHook", "Inference", "Evaluation"],
        subtitles=[
            "story_generator.py\n100/emotion",
            "vector_extraction.py\nActivationCollector,\nmean-pool from tok 50",
            "cross-emotion baseline\nemotion_vec = mean(this)\n- mean(all)",
            "steering.py\nSteeringHook\nregister_forward_hook",
            "steering.py\ngenerate_with_steering",
            "steering.py\nmeasure_refusal_rate",
        ],
        save_path=OUT_DIR / "architecture.png",
        figsize=(15, 2.8),
    )

    # Single steering intervention at inference time. Best layer is emotion-specific
    # (found per-emotion via find_best_layer, e.g. confidence=21, guilt=14, fear=24 —
    # see results/emotion_refusal/geometric_metrics.json) — NOT a fixed universal layer.
    draw_pipeline(
        steps=["Prompt", "Layer N\n(best layer\nper emotion)", "Forward\nHook", "+ strength ×\nemotion vector", "Remaining\nLayers", "Output"],
        subtitles=[
            "",
            "found via\nfind_best_layer()",
            "SteeringHook\nintercepts\nlayer output",
            "additive steering,\nSteeringConfig.method\n= 'add'",
            "unmodified\nforward pass",
            "generated\ntext",
        ],
        save_path=OUT_DIR / "steering_pipeline.png",
        figsize=(14, 2.8),
    )


if __name__ == "__main__":
    main()
